##################################
# Compilation ShoppingSimulator  #
# Common                         #
##################################

comp:
	find src/ -name "*.java" -print | xargs javac -d build
	jar cvf ShoppingSimulatorCommon.jar -C build ShoppingSimulator

